frontend:
  - changed-files:
      - any-glob-to-any-file: 'frontend/**/*'

backend:
  - changed-files:
      - any-glob-to-any-file: 'backend/**/*'

documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'

infrastructure:
  - changed-files:
      - any-glob-to-any-file:
          - 'terraform/**/*'
          - 'docker-compose*.yml'
          - '**/Dockerfile'

ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'

tests:
  - changed-files:
      - any-glob-to-any-file:
      - 'backend/tests/**/*'
      - 'frontend/src/__tests__/**/*'
